---
name: get-status
on:
  push:
  workflow_dispatch:
env:
  date_cal: 500

jobs:
  set-config:
    runs-on: ubuntu-latest
    outputs:
      confJson: ${{ steps.set-config.outputs.confJson }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set configuration
        id: set-config
        run: |
          cat config.json | tr -d '\n' | jq -c
          list=$(cat config.json | tr -d '\n' | jq -c)
          echo "confJson=${list}" >> $GITHUB_OUTPUT       

  get-status:
    needs: set-config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{fromJson(needs.set-config.outputs.confJson).repository}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get pr-created-date
        run: |
          echo ${{ matrix.repo }}
          chmod +x ./tools/get-pr-created-date.sh
          ./tools/get-pr-created-date.sh ${{ env.date_cal }} ${{ matrix.repo }} ${{ secrets.GIT_PAT }}
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
          fetch-depth: 0
          token: ${{ secrets.GIT_PAT }}
          path: target
      - name: Check developper
        run: |
          cd ${{ github.workspace }}/target
          echo "start showing developper"
          git log | git shortlog -nse
          echo "finish showing developper" 
